### ISSUE TITLE
Got an unexpected keyword argument 'init_weights'

### ISSUE THREAD

**Issue by morawi** [chenyaofo/image-classification-codebase#1]
Hi, 

thanks for sharing the models. I tried a few and they worked. Yet, `repvgg_a0`, `repvgg_a1`, and `repvgg_a2`  threw the following error:

`TypeError: __init__() got an unexpected keyword argument 'init_weights'
Using cache found in C:\Users\xxx/.cache\torch\hub\chenyaofo_pytorch-cifar-models_master`

I am loading the model to my local machine (Winowds 10 Pro, PyTorch 1.8;  and torchvision.__version__
'0.9.1') using:

`model = torch.hub.load("chenyaofo/pytorch-cifar-models", model_name_, pretrained=True, progress=False) `

Further details on init_weights :

```
`File "C:\Users\xxx/.cache\torch\hub\chenyaofo_pytorch-cifar-models_master\pytorch_cifar_models\repvgg.py", line 225, in _repvgg
    model = RepVGG(num_blocks=num_blocks, width_multiplier=width_multiplier,
TypeError: __init__() got an unexpected keyword argument  init_weights 
```

Update: Clearly, the [ RepVGG(nn.Module)](https://github.com/chenyaofo/pytorch-cifar-models/blob/9751dd01a18d0c471b2c4522ae734757b6c94d8d/pytorch_cifar_models/repvgg.py#L162)  has no 'init_weights' 

But,     [kwargs['init_weights'] = False ](https://github.com/chenyaofo/pytorch-cifar-models/blob/9751dd01a18d0c471b2c4522ae734757b6c94d8d/pytorch_cifar_models/repvgg.py#L224) assume so.

**Comment by chenyaofo** [comment]
Thanks for your feedback. I have fixed this bug.

Currently, I can successfully run the following code on my local machine with PyTorch version: 1.8.0+cpu,
```
model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar10_repvgg_a0", pretrained=True, progress=False, force_reload=True)
```

**Comment by morawi** [comment]
> I have fixed this bug.

Thank you. Working!
